[package]
name = "planar_triangulation"
version = "0.1.0"
authors = ["BoilingNoob <morgandowd@teksavvy.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
